export enum CartActionType {
  ADD_TO_CART = "ADD_TO_CART",
  REMOVE_CART_ITEM = "REMOVE_CART_ITEM",
  TOGGLE_CART_ITEM_AMOUNT = "TOGGLE_CART_ITEM_AMOUNT",
  CLEAR_CART = "CLEAR_CART",
  COUNT_CART_TOTALS = "COUNT_CART_TOTALS",
}

export enum LayoutActionType {
  TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR",
  TOGGLE_CART = "TOGGLE_CART",
  OPEN_MODAL = "OPEN_MODAL",
  CLOSE_MODAL = "CLOSE_MODAL",
  OPEN_SUMMARY = "OPEN_SUMMARY",
  CLOSE_SUMMARY = "CLOSE_SUMMARY",
}
